name: Fable

on:
  push:
    branches:
    - main

jobs:

  Fable:
    name: Run Fable
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
      with:
        ref: main
    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dotnet tools
      run: dotnet tool restore
    - name: Setup node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install npm packages
      run: npm install
    - name: Compile F# to JS
      run: npm run build
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: js-action
        path: |
          dist/*
          action.yml
          README.md

  JavaScript:
    name: Commit JavaScript to `JS` branch
    needs: Fable
    runs-on: ubuntu-latest
    steps:
    - name: Checkout JS branch
      uses: actions/checkout@v3
      with:
        ref: JS
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: js-action
    - name: Move files out of `dist/` folder
      run: mv dist/* .
    - name: Remove `dist/` folder
      run: rm -r dist/
    - name: Commit JavaScript action
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated commit of compiled JS

  Action:
    name: Run action from the JS branch
    needs: JavaScript
    runs-on: ubuntu-latest
    steps:
    - name: Checkout JS branch
      uses: actions/checkout@v3
      with:
        ref: JS
    - name: Hello world action step
      uses: ./
      id: hello
      with:
        who-to-greet: 'Mona the Octocat'
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
